"""
Abstract interface for every Large Language Model backend.
"""

from __future__ import annotations

from abc import ABC, abstractmethod


class BaseLLMClient(ABC):
    """
    Abstract interface implemented by every LLM backend.

    Concrete implementations may use HuggingFace Transformers,
    ONNX Runtime GenAI, Qualcomm AI Hub, QNN Runtime, etc.

    Business logic must never depend on a specific runtime.
    """

    @abstractmethod
    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        max_new_tokens: int | None = None,
        temperature: float | None = None,
    ) -> str:
        """
        Generate a response from the language model.

        Parameters
        ----------
        system_prompt
            Instruction that defines the model's behaviour.

        user_prompt
            User/business request.

        max_new_tokens
            Optional generation limit.

        temperature
            Optional sampling temperature.

        Returns
        -------
        str
            Raw text generated by the model.
        """
        raise NotImplementedError