"""
Pydantic schemas used by the SUTRA AI module.

These schemas define the contract between:

Backend
    ↓
Feature Engineering
    ↓
Prompt Builder
    ↓
Phi-3 Mini
    ↓
Parser
    ↓
Backend

No runtime-specific code should appear here.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------
# Backend Input
# ---------------------------------------------------------------------


class Supplier(BaseModel):
    """Supplier information provided by the backend."""

    supplier_name: str
    price_per_unit: float = Field(gt=0)
    reliability_score: float = Field(ge=0, le=100)
    lead_time_days: int = Field(ge=0)


class Festival(BaseModel):
    """Upcoming festival information."""

    name: str
    days_away: int = Field(ge=0)


class BusinessContext(BaseModel):
    """
    Complete inventory context received from the backend.
    """

    item: str

    remaining_weight: float

    reorder_threshold: float

    unit: str

    avg_daily_sales: float

    sales_trend: list[float]

    suppliers: list[Supplier]

    upcoming_festivals: list[Festival] = Field(default_factory=list)

    timestamp: datetime


# ---------------------------------------------------------------------
# Engineered Business Features
# ---------------------------------------------------------------------


class EngineeredContext(BaseModel):
    """
    Deterministic business intelligence generated before
    prompting Phi-3.
    """

    days_until_stockout: float

    inventory_status: str

    sales_trend: str

    average_recent_sales: float

    cheapest_supplier: str

    fastest_supplier: str

    most_reliable_supplier: str

    festival_near: bool

    festival_name: str | None = None

    festival_days: int | None = None

    festival_risk: str

    business_signals: list[str]


# ---------------------------------------------------------------------
# Recommendation Output
# ---------------------------------------------------------------------


class Recommendation(BaseModel):
    """
    Structured recommendation returned by Phi-3.
    """

    recommendation: str

    supplier: str

    quantity: float

    unit_price: float

    total_cost: float

    savings: float

    reasoning: str

    confidence: int = Field(ge=0, le=100)

    expected_delivery_days: int


# ---------------------------------------------------------------------
# Internal AI State
# ---------------------------------------------------------------------


class AgentState(BaseModel):
    """
    Internal state maintained by the AI pipeline.

    This object is never returned to the backend.
    It is reused during follow-up conversations.
    """

    recommendation: Recommendation | None = None

    engineered_context: EngineeredContext


# ---------------------------------------------------------------------
# Conversation
# ---------------------------------------------------------------------


class ConversationRequest(BaseModel):
    """
    Request received from the frontend when the
    shopkeeper asks a follow-up question.
    """

    question: str

    context: BusinessContext

    state: AgentState


class ConversationResponse(BaseModel):
    """
    Natural language response generated by Phi-3.
    """

    answer: str